### ISSUE TITLE
Make MPI optional

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#15]
We should only compile `gapmpi` if enabled by, say `--with-mpi`

**Comment by markuspf** [comment]
Could MPI possibly become a package as well? There seem to be functions called from gap.c to setup MPI.

**Comment by markuspf** [comment]
@alex-konovalov thinks we could even discontinue MPI support in favour of `zeromq` and `scscp`, as MPI doesn't have any benefits over those.

**Comment by fingolfin** [comment]
I have no particular oppinion on this, and don't even know how to test MPI, so that makes it somewhat tempting... OTOH, before we do that, we should ask if anybody is using that!

BTW, this might be helpful if we decide to keep it: https://www.gnu.org/software/autoconf-archive/ax_mpi.html

**Comment by ChrisJefferson** [comment]
@alex-konovalov : Do we even test GAP-MPI? Does it still work?

**Comment by fingolfin** [comment]
I think the pargap package is needed for this, and I used it last in 2012, back then it was working.

Perhaps we should ask on the mailing lists whether anybody is using it?

**Comment by olexandr-konovalov** [comment]
@fingolfin sorry - do not understand what is 'this' in 'pargap package is needed for this'. IIRC the plan was that MPI support in HPC-GAP will make pargap redundant. Maybe @vjanjic could help to clarify?

**Comment by fingolfin** [comment]
I wasn't even aware that HPC-GAP had made changes to the MPI support. I only looked at the top of `src/hpc/gapmpi.c` whch says `GAP source - ParGAP/MPI hooks` as well as `Copyright (C) 1999-2001  Gene Cooperman`

I just had a look at pargap's source. So, pargap's copy of `gapmpi.c` is quite close, only minimal changes have been made. Of course in order to get pargap to run, you had to compile your own version of GAP, which then contained a call to pargap's `InitGapmpi`... This is the part that was "always" in the kernel. I simply misremembered.

Anyway, the changes compared to pargap seem to be quite minimal. Was the work on this ever completed?

**Comment by fingolfin** [comment]
Closing this in favor of https://github.com/gap-system/gap/pull/1486 and https://github.com/gap-system/gap/pull/1487

Note in particular that my questions on the status of the MPI code above were never answered. If anybody still wants to do that, butter do it one of the two PRs linked above.
