### ISSUE TITLE
Teach GAP to "find itself", and use that to guess the location of the library.

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#20]
- one very simple step towards this is to store the $(top_srcdir)
    as a string in the GAP source, then use that as a default path (instead of PWD)
    to find the GAP library. Specifically, 
      SYS_DEFAULT_PATHS
    can be used for this purpose
 - However, upon "make install", we don't want $(top_srcdir) anymore, but rather
    something like $prefix/share/gap (or so)...
    This would require recompiling a file during installation...
 - in addition, the GAP executable could try to figure out its own location,
    and search relative to that. While this is not possible in a 100% portable
    fashion, even a 90% solution would help a lot.
    In fact, DoFindMyself() already implements something like this?!

**Comment by fingolfin** [comment]
This PR by @ChrisJefferson is also relevant: https://github.com/gap-system/gap/pull/802

**Comment by fingolfin** [comment]
For now, I reverted the HACK which added the `top_srcdir` to `SYS_DEFAULT_PATHS` -- instead, one now has to use `bin/gap.sh` again. The big advantage of that is of course that in order to install GAP, we only have to re-generate this trivial shell script, not recompile GAP.

And the part were GAP finds itself already is in gap-system#802
