### ISSUE TITLE
What to do about library paths? separate --with-X or CFLAGS/CPPFLAGS/LDFLAGS, both?

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#29]
I can get readline support and gmp to be detected and linked by setting `CPPFLAGS="-I /usr/local/include"` and `LDFLAGS="-L /usr/local/lib"`.

There is obviously a point in being able to supply separate paths for certain libraries with "--with-" flags (gc, atomic_ops, gmp).

I was trying to add options for readline, as in "--with-readline[=DIR|check]", but I am not sure whether this is the correct thing to do (and whether we manually program this for every library?)

**Comment by fingolfin** [comment]
Well, specifing paths as `--with-FOO=DIR` is mostly useful if every FOO really has a separate prefix. Otherwise, it's more convenient to just do
`./configure CPPFLAGS="-IDIR/include" LDFLAGS="-LDIR/lib"`
This is also more flexible.

However, this requires the user to have more knowledge about such things; for people who are not super experience with stuff like CPPFLAGS etc., being able to specify `--with-FOO=DIR` is likely a helpful boon. Which is why `--with-gmp` already supports this. So you could use the code for that as template for other flags.

Now, one more thing: Some people like their `--with-FOO` checks to do something special if no DIR argument is supplied: Instead of simply trying to use the lib without modifying CPPFLAGS / LDFLAGS, they teach it to search through a list of certain "standard" prefix paths, e.g. `/usr/local /opt`, and try each of those subsequently, until a match is found, or we give up.

One advantage (the only one, I think?) of this approach is that it means some more people can compile GAP "out of the box", without passing any flags. Indeed, some people expect (nay, _demand_ :-) that anything installed into `/usr/local` is picked up automatically.

The drawback is that it complicates detection, and (as every "magic" solution) can lead to confusing, hard to debug problems (e.g. if GAP picks up the wrong version of a library, one which the user perhaps was not even aware of).

Anyway, for now I'd not worry about the latter, and just go with the way I used for --with-gmp. If we want something more fancy, we can write a macro to do it (or perhaps "borrow" an existing one from https://www.gnu.org/software/autoconf-archive/).

**Comment by fingolfin** [comment]
For libraries that have a `FOO-config` script, we could also use https://www.gnu.org/software/autoconf-archive/ax_path_generic.html  -- and similar for pkgconfig enabled libraries.

Unfortunately, I don't think any of the ones we use do either... :-(

**Comment by fingolfin** [comment]
This is an example of a macro that does all kinds of fancy things, like explicitly searching through `/usr /usr/local /opt` and also checking for a minimal version of the library:
 https://www.gnu.org/software/autoconf-archive/ax_lib_sqlite3.html

Of course there are many more examples out there. But I am somewhat sceptical how useful this _really_ is... I'd ignore it for now

**Comment by fingolfin** [comment]
So in summary, I think the answer is that we want some simple `--with-FOO=PATH` flags supported, see issue #56.
