### ISSUE TITLE
Make it possible to compile files with `gap -C`

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#3]
At the moment there is a fairly involved script `gac.sh` that does this.

**Comment by fingolfin** [comment]
The `gac` script is actually not that involved. It simply provides a nice and flexible interface to this functionality. I am not sure whether we would gain anything by building this directly into GAP.

As it is, it is unclear to me what the scope of this issue is meant to be.  When you say "compile files", what kind of files do you have in mind for the input(s), and what for the output(s)? Note that gac currenlty supports GAP files, C/C++ files and object files as input, and can output C sources, object files (.o) and loadable modules (.so).

I guess one can argue that it should not bother to generate .o and .so files, as those should be handled by the build system of a given package (using autotools / libtool / cmake / whatever). But then we need to convince athors of affected packages to migrate their build systems (see also #39).

For now, I am looking into reviving `gac`, because I don't want to delay the merge by writing much new functionality.

**Comment by fingolfin** [comment]
I just added a `docomp` target which works by directly invoking `gap` and which translates `lib/type1.g` to `src/c_type1.g` etc.

So I really am not sure what you are asking for here. Closing for now, feel free to reopen with an explanation.
