### ISSUE TITLE
Update bundled libgc from 7.4.2 to 7.4.4 or even 7.6.0?

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/gap#42]
I guess moving to 7.4.4 is safe, but what about 7.6.0?

**Comment by fingolfin** [comment]
Any thoughts, @rbehrends?

**Comment by rbehrends** [comment]
7.6.0 has some interesting new changes, such as proper thread-local allocation for typed memory (where we are currently using a workaround).

The patch that we are using on top of the GC currently fails, because there have been minor changes to the way it uses mmap(). If we address that, it should work.

**Comment by fingolfin** [comment]
For now, I decided to use 7.4.4, as that is closer to what we have so far. And `gc-7.4.2-tl.patch` applies cleanly.

But I still wonder what `gc-7.4.2-tl.patch` *does*... I vaguely recall asking @rbehrends this before, and I am sure he answered, but I can't find an email with that anymore...

@rbehrends Could you please once again explain this, roughly?

**Comment by rbehrends** [comment]
The purpose of `gc-7.4.2-tl.patch` is to make thread-local allocation more efficient, by allowing the GC to work with block sizes greater than the physical pagesize. Thread-local allocation works by allocating a pool of small blocks, and the size of the block is `HBLKSIZE`. Normally, this is the physical page size, and this can mean too much overhead/contention for allocation, especially on a 64-bit machine. The patch allows you to increase the value of `HBLKSIZE` (and also has a larger default value).

The following changes occur as a result of the patch.

1. `GC_page_size` is set to `HBLKSIZE` if it's greater.
2. All `mmap()` allocations are aligned to multiples of `GC_page_size = HBLKSIZE`.
3. The mark stacks are allocated in static BSS memory rather than on the stack (and themselves excluded from scanning) in order to prevent the stack from overflowing.
4. `CPP_LOG_HBLKSIZE` Is set correctly for values of HBLKSIZE up to 2^18.

**Comment by fingolfin** [comment]
@rbehrends Thanks for the explanation. I wonder if we'd have any chance of convincing upstream to include these changes in a future releases.

**Comment by rbehrends** [comment]
Well, 7.6.0 has improved handling of thread-local allocations, so the patch may not be necessary anymore. We'd first have to test/benchmark that, though.

**Comment by markuspf** [comment]
currently on my system (dragonflybsd) GAP segfaults in `AllocateBagMemory` with gc-7.6

**Comment by fingolfin** [comment]
The bundled version is now 7.4.4. I have not looked at 7.6.0, that's for the future.
