### ISSUE TITLE
Include paths in wrong order for HPC-GAP build (?)

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#8]
When building an HPC-GAP, the following occiurs:

```
   C        gen/src/c_filt1.o
gen/src/c_filt1.c: In function 'HdlrFunc1':
gen/src/c_filt1.c:578:2: warning: implicit declaration of function 'STARTLINE_BODY' [-Wimplicit-function-declaration]
  STARTLINE_BODY(t_4) = INTOBJ_INT(39);
```

This seems to be an unholy alliance of the wrong `code.h` being included (namely the one from `src/gap`, and code hasn't been merged yet between `master` and `hpcgap-default`. 

Maybe we need a "bootstrap" target that does not use the `c_` files at all to compile the compiler to compile the `c_` files.

**Comment by markuspf** [comment]
There is also an issue when I give CFLAGS/LDFLAGS on the configure line:

```
../../configure CFLAGS="-I /usr/local/include" ...
```

puts `/usr/local/include` in front of the GAP-specific includes. Now my `/usr/local/include` contains a file `profile.h`...

**Comment by markuspf** [comment]
Mhm. I wonder why this works on a normal build, but not with `--enable-hpcgap`

**Comment by markuspf** [comment]
Ok, this would be because in the standard build we don't have code.c be in `gen/`, hence `profile.h` is in the same directory...

**Comment by markuspf** [comment]
The problem (unsurprisingly) occurs regardless of whether I give `CFLAGS` on the command line of `configure`.

**Comment by fingolfin** [comment]
This is my fault, and I already have a fix (though we may want to use a different one).

The problem is that `#include "..."` _always_ looks first in the current directory -- i.e. the directory from which the current compile unit comes. So if `src/foo.c` does `#include "bar.h"`, it always first looks for `src/bar.h` -- even though in HPC-GAP mode, we may want it to use `hpcgap/src/bar.h` instead.

So, my "clever" solution for dealing with HPC-GAP mode, which involved using `-Ihpcgap/src` etc. switches, does not quite work :-(.

The easiest solution (the one I implemented locally) is to change all `#include "..."` to `#include <...>`. I would do this once, in a comit performed by the `redo` shell script, with a simple regex and perl.

I see no drawback of that, actually, except that some people have the incorrect believe that `#include <...>` is reserved for system headers (it most definitely is not), and thus might object to it...

Other solution would involve symlinking and/or copying all .c and .h files into the gen/ dir, but I somewhat dislike that, as it makes it difficult to track things, and very easy to get wrong...

**Comment by fingolfin** [comment]
I'll just implement the solution I just proposed; since it is scripted, I can easily revert it should we discover serious issues with it.

On a related note, I'd really like to change all `#include "foo.h"` to `#include <src/foo.h>`, too... Again, with a script... my only concern is that this might break compilation of some packages, so I'll investigate that first.

**Comment by markuspf** [comment]
When will this be available? I am trying to get HPC-GAP to build, but there seem to be many little things wrong with includes, and I am a bit undecided as to where I would put the fixes (or, sometimes, I am not even sure what the correct fix would be).

I could just start committing to `hpcgap-default`, but I am not sure that's a very good option at the moment?

**Comment by fingolfin** [comment]
Resolved now
