### ISSUE TITLE
Add appropriate -D flags for HPC-GAP build

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#9]
We need to `#define` at least `HPCGAP` and `MAX_GC_THREADS` to build HPC-GAP

**Comment by markuspf** [comment]
I see that `HPCGAP` is already defined and that there is a FIXME comment in configure.ac. I'll investigate which flags we actually need at the moment.

**Comment by fingolfin** [comment]
We definitely need to define `MAX_GC_THREADS` -- I just had a look, and it seems we might want to add a `--with-gcmaxthreads=NUM` flag (with NUM and integer).

Then again, @rbehrends might be unhappy about this, because it would require re-running `./configure && make` to change the variable; as I understand it (but I might be wrong), he took some care so that one can very quickly change the `gcmaxthreads` resp. `MAX_GC_THREADS` variable without recompiling.

Well, we can achieve that, too: By both providing `--with-gcmaxthreads=NUM` as a configure flag; but then _also_ allowing to override this via, say `make MAX_GC_THREADS=123`. The latter requires a little care, to detect the changed configuration value, but this is certainly doable (the git.git build system does something like this, and I am confident that I can replicate it).

The former is much easier than the latter, though, hence I'd go with that for starters. Note that if `--with-gcmaxthreads=NUM` is not specified, then this should revert to some default value. The default value in the scons build system is either 32, or `ncpus`, i.e. the number of CPUs ... ?!? So perhaps we also want to add code to configure to detect the number of CPUs (this can't be done in a very portable fashion, I am afraid, but we can imitate what Reimer did in his `SConstruct` file... just grep for `ncpus`

**Comment by markuspf** [comment]
I looked at the code and one can change the number of GC threads via an environment variable. It looks as if the MAX_GC_THREADS is just a compiled-in upper bound for how many mark threads are allowed.

The number of threads (and I believe this was just for worker threads) was always configurable via a command-line switch (-P) in HPC-GAP, the detected number of CPUs "just" takes care of the default.

**Comment by fingolfin** [comment]
Regarding default values for MAX_GC_THREADS, this might be helpful: https://www.gnu.org/software/autoconf-archive/ax_count_cpus.html

**Comment by fingolfin** [comment]
Are there any other #defines we should set? If so, I think we should list them explicitly, and/or make dedicated issues for them. Else we can never close this issue :-)

**Comment by markuspf** [comment]
I managed to build an HPC-GAP executable with just `MAX_GC_THREADS` defined, but I need to look at where the other `GC` build options went that are in the `SConstruct` build for HPC-GAP, likely they went into building custom versions of `boehm-gc`.

**Comment by markuspf** [comment]
I just checked and it is indeed the case that the other parameters in the SConstruct build went into building custom `libgc`. There also seems to be a patch applied to `libgc`, which would suggest we need to bundle and build `libgc`...

But on the upside, I believe this issue can be closed now.

**Comment by rbehrends** [comment]
The `MAX_GC_THREADS` #define only exists as a safety valve so that you don't accidentally start a lot of threads and have performance degrade (and the GC also has its own internal limit). Putting that in a `./configure` option would be completely okay, I think.

**Comment by fingolfin** [comment]
Actually, I don't think `MAX_GC_THREADS` makes much sense as a configure option either. Instead, I think GAP should detect the number of processors at runtime; and there should be a command line option to set the number of GC thread and/or MAX_GC_THREADS

**Comment by fingolfin** [comment]
... and re-reading older comments, it seems such an option already exists. But again: The number of CPUs should be detected by GAP at runtime, not by configure. After all, the machine running GAP may be a different one than the one which built it. This is indeed quite comment for binary distros, or for GAP installtions on a network share.

**Comment by fingolfin** [comment]
Closing. But see also https://github.com/gap-system/gap/issues/1219 (and if anybody feels anything else in here warrants looking into: Please don't hesitate to open a new issue on the GAP issue tracker)
